// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_gen

import (
	"time"
)

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}
